from django.urls import path
from ucl.views import (
    activity_views,
    experiment_views,
    guide_views,
    laboratory_views,
    option_views,
    parameter_views,
    procedure_views,
    session_views,
    solved_activity_views,
    media_experiment_views,
)

app_name = "ucl"

urlpatterns = [
    path(
        "laboratories/",
        laboratory_views.ListCreateLaboratoryView.as_view(),
        name="laboratory_list_create",
    ),
    path(
        "laboratories/<uuid:pk>/",
        laboratory_views.RetrieveUpdateDestroyLaboratoryView.as_view(),
        name="laboratory_detail",
    ),
    path(
        "laboratories/<uuid:pk>/guides/",
        laboratory_views.ListLaboratoryGuidesView.as_view(),
        name="laboratory_guides",
    ),
    path(
        "laboratories/<uuid:pk>/parameters/",
        laboratory_views.ListLaboratoryParametersView.as_view(),
        name="laboratory_parameters",
    ),
    path(
        "laboratories/<uuid:pk>/experiments/",
        laboratory_views.ListLaboratoryExperimentsView.as_view(),
        name="laboratory_experiments",
    ),
    path(
        "laboratories/<uuid:pk>/activities/",
        laboratory_views.ListLaboratoryActivitiesView.as_view(),
        name="laboratory_activities",
    ),
    path(
        "laboratories/<uuid:pk>/sessions/",
        laboratory_views.ListLaboratorySessionsView.as_view(),
        name="laboratory_sessions",
    ),
    path(
        "guides/",
        guide_views.CreateGuideView.as_view(),
        name="guide_create",
    ),
    path(
        "guides/<uuid:pk>/",
        guide_views.RetrieveUpdateDestroyGuideView.as_view(),
        name="guide_detail",
    ),
    path(
        "parameters/",
        parameter_views.CreateParameterView.as_view(),
        name="parameter_create",
    ),
    path(
        "parameters/<uuid:pk>/",
        parameter_views.RetrieveUpdateDestroyParameterView.as_view(),
        name="parameter_detail",
    ),
    path(
        "experiments/",
        experiment_views.ExperimentCreateView.as_view(),
        name="experiment_create",
    ),
    path(
        "experiments/<uuid:pk>/",
        experiment_views.ExperimentDetailView.as_view(),
        name="experiment_detail",
    ),
    path(
        "experiments/filter/",
        experiment_views.ExperimentRetrieveByOptionIdsView.as_view(),
        name="experiment_by_option_ids",
    ),
    path(
        "experiments/<uuid:pk>/activities/",
        experiment_views.ListExperimentActivitiesView.as_view(),
        name="experiment_activities",
    ),
    path(
        "options/<uuid:pk>/",
        option_views.RetrieveUpdateDestroyOptionView.as_view(),
        name="option_detail",
    ),
    path(
        "experiments/media/<uuid:pk>/",
        media_experiment_views.RetrieveUpdateDestroyMediaExperimentView.as_view(),
        name="experiment_media",
    ),
    path(
        "activities/",
        activity_views.CreateActivityView.as_view(),
        name="activity_create",
    ),
    path(
        "activities/<uuid:pk>/",
        activity_views.RetrieveUpdateDestroyActivityView.as_view(),
        name="activity_detail",
    ),
    path(
        "sessions/",
        session_views.ListCreateSessionView.as_view(),
        name="guide_list_create",
    ),
    path(
        "sessions/<uuid:pk>/",
        session_views.RetrieveUpdateDestroySessionView.as_view(),
        name="session_detail",
    ),
    path(
        "sessions/<uuid:pk>/solved-activities/",
        session_views.ListSessionSolvedActivitiesView.as_view(),
        name="session_solved_activities",
    ),
    path(
        "sessions/<uuid:session_pk>/activities/<uuid:activity_pk>/solved-activities/",
        session_views.ListSessionActivitySolvedActivitiesView.as_view(),
        name="session_activity_solved_activities",
    ),
    path(
        "solved-activities/",
        solved_activity_views.ListCreateSolvedActivityView.as_view(),
        name="guide_list_create",
    ),
    path(
        "solved-activities/<uuid:pk>/",
        solved_activity_views.RetrieveUpdateDestroySolvedActivityView.as_view(),
        name="solved_activity_detail",
    ),
    path(
        "procedures/<uuid:pk>/",
        procedure_views.RetrieveUpdateDestroyProcedureView.as_view(),
        name="procedure_detail",
    ),
]
