from django.urls import path
from ucl.views import (
    laboratory_views,
    guide_views,
    parameter_views,
    option_views,
    experiment_views,
    video_experiment_views,
    activity_views,
)

app_name = "ucl"

urlpatterns = [
    path(
        "laboratories/all/",
        laboratory_views.ListAllLaboratoryView.as_view(),
        name="laboratory_list_all",
    ),
    path(
        "laboratories/",
        laboratory_views.ListCreateLaboratoryView.as_view(),
        name="laboratory_list_create",
    ),
    path(
        "laboratories/<uuid:pk>/",
        laboratory_views.RetrieveUpdateDestroyLaboratoryView.as_view(),
        name="laboratory_detail",
    ),
    path(
        "laboratories/<uuid:pk>/guides/",
        laboratory_views.ListLaboratoryGuidesView.as_view(),
        name="laboratory_guides",
    ),
    path(
        "laboratories/<uuid:pk>/parameters/",
        laboratory_views.ListLaboratoryParametersView.as_view(),
        name="laboratory_parameters",
    ),
    path(
        "laboratories/<uuid:pk>/experiments/",
        laboratory_views.ListLaboratoryExperimentsView.as_view(),
        name="laboratory_experiments",
    ),
    path(
        "laboratories/<uuid:pk>/activities/",
        laboratory_views.ListLaboratoryActivitiesView.as_view(),
        name="laboratory_activities",
    ),
    path(
        "guides/",
        guide_views.CreateGuideView.as_view(),
        name="guide_create",
    ),
    path(
        "guides/<uuid:pk>/",
        guide_views.RetrieveUpdateDestroyGuideView.as_view(),
        name="guide_detail",
    ),
    path(
        "parameters/",
        parameter_views.CreateParameterView.as_view(),
        name="parameter_create",
    ),
    path(
        "parameters/<uuid:pk>/",
        parameter_views.RetrieveUpdateDestroyParameterView.as_view(),
        name="parameter_detail",
    ),
    path(
        "experiments/",
        experiment_views.ExperimentListCreateView.as_view(),
        name="experiment_list_create",
    ),
    path(
        "experiments/<uuid:pk>/",
        experiment_views.ExperimentDetailView.as_view(),
        name="experiment_detail",
    ),
    path(
        "experiments/filter/",
        experiment_views.ExperimentRetrieveByOptionIdsView.as_view(),
        name="experiment_by_option_ids",
    ),
    path(
        "experiments/<uuid:pk>/activities/",
        experiment_views.ListExperimentActivitiesView.as_view(),
        name="experiment_activities",
    ),
    path(
        "options/<uuid:pk>/",
        option_views.RetrieveUpdateDestroyOptionView.as_view(),
        name="option_detail",
    ),
    path(
        "experiments/videos/<uuid:pk>/",
        video_experiment_views.RetrieveUpdateDestroyVideoExperimentView.as_view(),
        name="option_detail",
    ),
    path(
        "activities/",
        activity_views.CreateActivityView.as_view(),
        name="activity_create",
    ),
    path(
        "activities/<uuid:pk>/",
        activity_views.RetrieveUpdateDestroyActivityView.as_view(),
        name="activity_detail",
    ),
]
