# Generated by Django 4.0 on 2024-11-05 15:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_create_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement', models.CharField(max_length=500)),
                ('expected_result', models.CharField(default=None, max_length=500, null=True)),
                ('unit', models.CharField(default=None, max_length=20, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('data_file', models.FileField(default=None, null=True, upload_to='')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_laboratories', to='users.user')),
            ],
            options={
                'verbose_name_plural': 'Laboratories',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('laboratory', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_sessions', to='ucl.laboratory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='VideoExperiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_videos', to='ucl.experiment')),
            ],
            options={
                'verbose_name_plural': 'VideoExperiments',
            },
        ),
        migrations.CreateModel(
            name='SolvedActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=500)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_solved_activity', to='ucl.activity')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_solved_activities', to='ucl.session')),
            ],
            options={
                'verbose_name_plural': 'SolvedActivities',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('solved_activity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='solved_activity_procedures', to='ucl.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(default=None, max_length=20, null=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_parameters', to='ucl.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_options', to='ucl.parameter')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(default=None)),
                ('file', models.FileField(default=None, upload_to='')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_guides', to='ucl.laboratory')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_experiments', to='ucl.laboratory'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='parameter_options',
            field=models.ManyToManyField(related_name='options_experiments', to='ucl.Option'),
        ),
        migrations.AddField(
            model_name='activity',
            name='experiment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_activities', to='ucl.experiment'),
        ),
        migrations.AddField(
            model_name='activity',
            name='laboratory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_activities', to='ucl.laboratory'),
        ),
    ]
