# Generated by Django 4.0 on 2025-08-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
