# Generated by Django 4.0 on 2025-01-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='data',
            field=models.CharField(max_length=2500),
        ),
    ]
