# Generated by Django 4.0 on 2025-09-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucl', '0002_alter_guide_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='possible_answers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
