# Generated by Django 4.0 on 2025-09-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucl', '0003_activity_possible_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='possible_answers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
