# Generated by Django 4.0 on 2025-09-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucl', '0004_alter_activity_possible_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_procedure_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
